# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Hyangsuk Min
title: AI Research Engineer
# email: hyangsukmin503@gmail.com
# email_title: Gmail # (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  hmin0503
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: hyangsukmin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
googlescholar_username: U24LXHAAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/portrait.jpg # Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>
# - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project

  # - title: Publications
  #   layout: text
  #   content: |
  #       [c4] J. Nam, **H. Min**, J. Shin, J. Jung. S. Ko. TITLE. EVS37 2024.
  #       [c3] **H. Min**, and J. Lee, "Temporal Convolutional Network-Based Time-Series Segmentation," In Proc. 2023 IEEE Int'l Conf. on Big Data and Smart Computing (BigComp), Jeju, Korea, pp. 269 ~ 276, Feb. 2023 (regular paper).
  #       [c2] D. Kim, H. Min, Y. Nam, H. Song, S. Yoon, M. Kim, and J. Lee, "COVID-EENet: Predicting Fine-Grained Impact of COVID-19 on Local Economies," In Proc. 36th AAAI Conf. on Artificial Intelligence (AAAI), Virtual Event, pp. 11971 ~ 11981, Feb. 2022 (top conference, oral paper, acceptance rate: 15.0%). 
  #       [c1] M. Kim, J. Kang, D. Kim, H. Song, H. Min, Y. Nam, D. Park, and J. Lee, "Hi-COVIDNet: Deep Learning Approach to Predict Inbound COVID-19 Patients and Case Study in South Korea," In Proc. 26th ACM SIGKDD Int'l Conf. on Knowledge Discovery and Data Mining (KDD), Virtual Event, California, pp. 3466 ~ 3473, Aug. 2020 (top conference, AI for COVID track).
  - title: Experience
    layout: list
    content:
      - layout: left
        title: [HL Mando](https://www.hlmando.com/ko/solution/sw.do)
        sub_title: Engineer
        caption: October 2022 - present # Date Range (eg. November 2016 - present)
        # link:  # Link to company (optional)
        quote: >
          차량 샤시 제품 개발 및 소프트웨어 개발...
          # Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          1. SDV 위한 차량 예지보전 MLOps 개발
          2. Smart Factory 위한 부품 불량 탐지 Vision 모델 개발 및 MLOps 개발
          3. Smart Factory Vision 모델 데이터 불균형 문제 해소를 위한 GAN 활용
          4. LLM 활용 합성 데이터 생성 및 객체 탐지 모델 성능 향상
      - layout: left
        title: [Uniquify](https://www.uniquify.com)
        sub_title: Engineer
        caption: August 2018 - June 2019
        # link: 
        quote: >
          팹리스 회사로 반도체 칩 디자인, AI 반도체 개발
        description:
          1. TensorFlow 활용 AI Vision 개발 
          2. 반도체 칩 디자인 
          3. Perl 활용 데이터 요약
  
  - title: Education
    layout: list
    content:
      - layout: top-left # top-right
        title: KAIST 
        sub_title: MS in Data Science # (eg. BA Performing Arts)
        caption: 2020.03 - 2022.08 # Date Range (eg. 2016 - 2019)
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - GPA (4.12/4.3) # Description of qualification
          - Advisor: Jae-Gil Lee
      - layout: top- left # top-right
        title: Kookmin University
        sub_title: BS in Data Science # (eg. BA Performing Arts)
        caption: 2015.03 - 2019.08 # Date Range (eg. 2016 - 2019)
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - GPA (4.4/4.5) # Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",g
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
